//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cn
    {
        public string CNUUID { get; set; }
        public string ContractUUID { get; set; }
        public Nullable<sbyte> ConfidentialityContractFlag { get; set; }
        public string SupplierUUID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAddress { get; set; }
        public string SupplierSuburb { get; set; }
        public string SupplierPostcode { get; set; }
        public string SupplierState { get; set; }
        public string SupplierCountry { get; set; }
        public Nullable<bool> SupplierABNExempt { get; set; }
        public string ParentCNUUID { get; set; }
        public string MULUUID { get; set; }
        public string AmendmentReason { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string Division { get; set; }
        public string Branch { get; set; }
        public string OfficePostcode { get; set; }
        public string AgencyRefId { get; set; }
        public string SONUUID { get; set; }
        public Nullable<sbyte> ConfidentialityOutputsFlag { get; set; }
        public string ProcurementCode { get; set; }
    }
}
